---
title: "The Global Economic Shift"
author: "Quang VU"
date: '2022-06-25'
output:
  html_document:
    theme: paper
    highlight: kate
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, fig.showtext = T, fig.retina = 1)
```



```{r prep, message=FALSE}
## packages
library(tidyverse)
library(readxl)
library(janitor)
library(ggbump)
library(ggflags)
library(countrycode)
library(glue)
library(ggtext)


```


```{r data}
cebr.data <- na.omit(read_excel("E:/data/cebr World Economic League Table 2022.xlsx",na = "n/a") %>% clean_names())

cebr.data %>% 
  pivot_longer(cols = - country_name,
               names_to = "year",
               values_to = "rank") %>% 
  mutate(year = as.numeric(str_replace(year, "x", ""))) %>% 
  filter(rank <= 15 & year != 2022) %>% 
  group_by(rank,year) %>% 
  arrange(rank, desc = TRUE) %>% 
  mutate(
    country_code = str_to_lower(c(countrycode(country_name,
                                              origin = "country.name",
                                              destination = "genc2c"))
                                 )
  ) ->  cebr.rank

### country flags
country_flags_end <- data.frame(
  x = 2036, 
  y = 1:15, 
  country_name = str_to_lower(cebr.rank %>% filter( year == "2036") %>% arrange() %>% pull(country_code)),
  stringsAsFactors = FALSE)

country_flags_start <- data.frame(
  x = 2006, 
  y = 1:15, 
  country_name = str_to_lower(cebr.rank %>% filter( year == "2006") %>% arrange() %>% pull(country_code)),
  stringsAsFactors = FALSE)
```

```{r plot, fig.width = 5, fig.height = 6.5}
cebr.rank %>% 
  ggplot(aes(
    x = year,
    y= rank,
    colour = country_name
  )) +
  
  geom_line(size = 0.1) +
  
  geom_point(size = 6,alpha = 0.8) +
  
  geom_point(size = 5, alpha = 0.85) +
  
  geom_point(size = 3, alpha = 0.9) +
  
  geom_flag(
    data = country_flags_start, 
    aes(
      x = x,
      y = y,
      country = country_name,
      size = 6
    )
  ) +
  
  geom_flag(
    data = country_flags_end, 
    aes(x = x,
        y = y,
        country = country_name,
        size = 6
    )
  ) +
  
  scale_x_continuous(
    breaks = seq(2006,2036,5),
    labels = paste0(seq(2006,2036,5),c(rep("",4),rep("p",3)))
  )+
  
  scale_y_reverse(breaks = 1:15, sec.axis = dup_axis())+
  
  scale_color_manual(
    values = c(
      Australia = "#7B4173",
      Brazil = "#E5550E",
      Canada = "#8B6D31",
      China = "#990F26",
      France = "#7ABECB",
      Germany = "#A2CC7A",
      India = "#3D0E98",
      Indonesia = "#A9B4AE",
      Italy = "#957ACB",
      Japan = "#54980F",
      Korea = "#E6B952",
      Mexico = "#42847A",
      Russia = "#FC8B3B",
      Spain = "#CE6DBC",
      `United Kingdom` = "#CC7A88",
      `United States` = "#0F8199"
    )
  ) +
  
  labs(
    title = glue("<span style='font-family: serif; color: black; font-size: 48px'>
                  The Global \\
                 \nEconomic Shift 
                  </span>"),
    subtitle = glue("<span style='font-family: sans; color: #A9B4AE; font-size: 14px'>
                    Economies Ranked by Projected GDP 
                    </span>", 
                    "<span'> \\
                    \nThe world economy continue to grow, and expected to soar past $100 trillion this year.                           </span>",
                    "<span'> \\
                    \nBy 2035, the World's GDP will double, and 
                    </span>",
                    "<span style='color:#990F26'><strong>China</strong></span>.",
                    " is likely to become the largest economy by 2030."),
    y = NULL,
    x = NULL,
    caption = "Visualization by Quang.VU • Data from CEBR")  +
  
  theme(
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    panel.background = element_rect(fill= "white", color = "white"),
    plot.title = element_markdown(),
    plot.subtitle = element_markdown(size = 6)
    )


```




















































































